//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meeting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
    
        public virtual Message Message { get; set; }
    }
}
