//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meeting.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MeetingContainer : DbContext
    {
        public MeetingContainer()
            : base("name=MeetingContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chat> ChatSet { get; set; }
        public virtual DbSet<Message> MessageSet { get; set; }
        public virtual DbSet<File> FileSet { get; set; }
        public virtual DbSet<User> UserSet { get; set; }
    }
}
