//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meeting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public System.Guid ID { get; set; }
        public string Content { get; set; }
        public System.DateTime SendingTime { get; set; }
        public string Status { get; set; }
    
        public virtual File File { get; set; }
        public virtual User User { get; set; }
    }
}
